[project]
name = "get-up"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pendulum>=3.1.0",
    "requests>=2.32.5",
]
